var H1List = [
  "gmail",
  "ubg365 games",
  "google font-Family",
  "removebg",
  "neal fun",
  "convert website",
  "chatgbt",
  "coolor",
  "webscripting test ",
  "youtube dowload video",
  "animation for iphone(capcut)",
  "namify",
  "autoDraw",
  "erase object",
  "tiny wow",
  "meme generrator",
  "rate things",
  "hash",
  "lost gamer",
  "ui/ux design help",
  "PYTHON ROADMAP",
  "get free ready design",
  "sound effect",
  "text to speech",
  "best ui 2",
  "google slide",
  "dimensions 3d",
  "flaticon",
  "i love pdf",
  "egybest",
  "spline",
  "public api",
  "css btn",
  "bootstrap5",
  "video effect",
  "text to graphic",
  "desk design",
  "text to actress talks",
  "take design idea",
  "jsonpathfinder",
  "dribble",
  "slack",
  "uhdpaper",
  "Rapid api",
  "youtube"
];
var aHrefList = [
  "https://mail.google.com/mail/u/0/#inbox",
  "https://ubg365.github.io/",
  "https://fonts.google.com/",
  "https://www.remove.bg/",
  "https://neal.fun/",
  "https://cloudconvert.com/",
  "https://chatgpt.com/c/6728a5ce-7668-800a-90bd-f5d8e79e646e",
  "https://coolors.co/palettes/trending",
  "https://books.toscrape.com/",
  "https://ssyoutube.com/en787IC/",
  "https://app.rotato.app/all",
  "https://namify.tech/",
  "https://www.autodraw.com/",
  "https://cleanup.pictures/",
  "https://tinywow.com/",
  "https://imgflip.com/memegenerator",
  "https://tiermaker.com/",
  "https://emn178.github.io/online-tools/sha256.html",
  "https://lostgamer.io/",
  "https://uiverse.io/?search=button",
  "https://roadmap.sh/python",
  "https://www.kittl.com/templates",
  "https://mixkit.co/free-sound-effects/",
  "https://ttsmaker.com/",
  "https://magicui.design/",
  "https://docs.google.com/presentation/u/0/?pli=1",
  "https://www.dimensions.com/?r=0",
  "https://www.flaticon.com/",
  "https://www.ilovepdf.com/jpg_to_pdf",
  "https://i-egybest.com/",
  "https://app.spline.design/home",
  "https://github.com/public-apis/public-apis",
  "https://getcssscan.com/css-buttons-examples",
  "https://getbootstrap.com/docs/5.0/getting-started/introduction/",
  "https://videoeffects.com/browse",
  "https://app.napkin.ai/page/CgoiCHByb2Qtb25lEiwKBFBhZ2UaJGM1NzQ2ZTAwLTJmYzMtNDQ5My05MTQxLTM5YjE4YWQ5YzVhMw",
  "https://deskspacing.com/",
  "https://getyarn.io/",
  "https://www.landingfolio.com/",
  "https://jsonpathfinder.com/",
  "https://dribbble.com/shots",
  ":https://app.slack.com/client/T07UAAZBR41/C07U05R2FRS",
  "https://www.uhdpaper.com/",
  "https://rapidapi.com/hub",
  "youtube.com"
];

var article = document.querySelector("article");

for (i = 0; i < H1List.length; i++) {
  article.innerHTML += `
        <div> 
             <h1>${H1List[i]} </h1>
             <a id='click' target='blank' href= "${aHrefList[i]}">visit</a>
        </div>  
    `;
}
